#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Aninda Sundar Howlader
"""
WHY THIS FILE EXISTS
====================
Because a README is the one file everybody reads and nobody maintains.

Every number in the two READMEs this writes is COUNTED from the repository at
build time — cards, themes, tokens, chapters, pages. None is typed.

That is not tidiness. Twice already in this project a hand-written statement of
fact went stale and started lying: the site's list of missing Bangla still claimed
twenty-five card names were absent after every one had been filled in, and a
comment asserted a Chromium failure that turned out never to have been tested. A
sentence a human wrote once and nobody re-reads is the least reliable thing in a
repository, and a README is made almost entirely of those.

So the prose is written here and the facts are looked up here, together, and CI
regenerates the files and fails on any difference.

RUN
---
    cd /Users/gru953/Claude/Cowork/Aninda_Studio
    ./.venv/bin/python scripts/readme.py
    ./.venv/bin/python scripts/readme.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

EMAIL = "aninda.sh15@gmail.com"
REPO = "https://github.com/GRU-953/aninda-studio"
SITE = "https://anindastudio.com"
PKG = "aninda-studio-tokens"


def count() -> dict:
    """Every figure in the README, read from the thing it describes."""
    f: dict = {}

    reg = json.loads((ROOT / "08_components" / "_cards.json").read_text())
    cards = reg["cards"] if isinstance(reg, dict) and "cards" in reg else reg
    f["cards"] = len(cards)
    for g in ("Foundations", "Components", "Patterns"):
        f[g.lower()] = sum(1 for c in cards if c["group"] == g)
    f["cards_bn"] = sum(1 for c in cards if c.get("name_bn"))

    css = (ROOT / "07_tokens" / "css" / "tokens.css").read_text()
    f["tokens"] = len(set(re.findall(r"--as-[a-z0-9-]+", css)))
    f["themes"] = len(re.findall(r'\[data-theme="[a-z-]+"\] \{', css))

    proof = json.loads((ROOT / "05_colour" / "generated" / "estuary.proof.json").read_text())
    roles = [r for t in proof["themes"].values() for r in t["roles"].values()]
    f["pairs"] = len(roles)

    # Text and non-text are counted SEPARATELY, and this is not fussiness.
    # Reporting one minimum across both produced a README that said "the lowest
    # anywhere is 3.81:1, against a floor of 4.5:1" — which reads as the system
    # failing its own standard. That 3.81 is a border, and WCAG 1.4.11 asks 3:1 of
    # a border and defines no AAA level for it at all. Comparing a non-text role
    # to the text floor is a category error, and it is the same one the colour
    # engine had to be corrected for. Prose can make it just as easily as code.
    f["worst_text"] = min(r["worst_case_lsb"] for r in roles if r["kind"] == "text")
    f["worst_nontext"] = min(r["worst_case_lsb"] for r in roles if r["kind"] == "nontext")
    f["n_text"] = sum(1 for r in roles if r["kind"] == "text")
    f["n_nontext"] = sum(1 for r in roles if r["kind"] == "nontext")

    gb = ROOT / "09_guidebook" / "Aninda-Studio-Guidebook.html"
    f["guidebook_mb"] = round(gb.stat().st_size / 1_000_000, 1) if gb.exists() else 0
    pdf = ROOT / "09_guidebook" / "Aninda-Studio-Guidebook.pdf"
    f["pdf_mb"] = round(pdf.stat().st_size / 1_000_000, 1) if pdf.exists() else 0
    build = (ROOT / "09_guidebook" / "build.py").read_text()
    f["chapters"] = len(re.findall(r'^\s*\("\d\d", "', build, re.M))

    f["assets"] = len(list((ROOT / "10_assets").glob("*.png"))) + \
                  len(list((ROOT / "10_assets").glob("*.ico"))) + \
                  len(list((ROOT / "10_assets").glob("*.svg")))
    f["marks"] = len(list((ROOT / "04_mark" / "svg").glob("*.svg")))
    f["files"] = sum(1 for p in ROOT.rglob("*") if p.is_file()
                     and not any(x in p.parts for x in
                                 (".venv", "node_modules", "browsers", ".git", "candidates")))
    return f


def english(f: dict) -> str:
    return f"""<!-- GENERATED by scripts/readme.py — do not hand-edit.
     Every number below is counted from the repository, not typed.
     Regenerate: ./.venv/bin/python scripts/readme.py -->

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="10_assets/README-header-dark.png">
    <img src="10_assets/README-header-light.png" alt="Aninda Studio" width="640">
  </picture>
</p>

# Aninda Studio

**A brand and a design system, built by one person and measured rather than
asserted.**

*অনিন্দ্য স্টুডিও · [বাংলায় পড়ুন](README.bn.md)*

[![System: Apache-2.0](https://img.shields.io/badge/system-Apache--2.0-0D1A17)](LICENSE)
[![Writing: PolyForm NC](https://img.shields.io/badge/writing-PolyForm%20NC%201.0.0-115E68)](LICENSE-DOCS.md)
[![Fonts: OFL 1.1](https://img.shields.io/badge/fonts-OFL%201.1-115E68)](NOTICE)

I make small, careful software. This is the design system it is built on, and the
brand that sits on top of it. Where something here has a limit, the limit is
written down rather than left for you to find.

## The one thing to understand

**Every colour pairing in this system was measured, not chosen.**

There are **{f['pairs']} colour role and theme pairings** across
**{f['themes']} themes** — light, dark, and a high-contrast pair. Each one was
measured against every surface it can land on, on the rounded 8-bit hex a browser
actually produces, and then measured again with every channel of both colours
nudged by one bit. The published figure is the worst of those results.

- **{f['n_text']} text pairings.** The lowest is **{f['worst_text']}:1**, against a
  floor of 4.5:1 (WCAG 2.2 SC 1.4.3) in the ordinary themes and 7:1 (SC 1.4.6) in
  the high-contrast ones.
- **{f['n_nontext']} non-text pairings** — borders and focus rings. The lowest is
  **{f['worst_nontext']}:1**, against a floor of 3:1 (SC 1.4.11).

Those two are counted separately on purpose. **WCAG defines no AAA level for
non-text contrast**, so a border at 3.9:1 has fully met its criterion; judging it
against the 4.5:1 text threshold would call a pass a failure.

That is why there are no hand-written contrast figures in this repository. A
number a person types is a number that can be wrong and stay wrong.

## What is in here

| Folder | What it holds |
|---|---|
| `09_guidebook/` | **The guidebook.** {f['chapters']} chapters in English and Bangla, one self-contained HTML file ({f['guidebook_mb']} MB) that needs no network, plus a {f['pdf_mb']} MB PDF |
| `07_tokens/` | The design tokens: DTCG source, and {f['tokens']} CSS custom properties generated from it |
| `08_components/` | {f['cards']} component and pattern cards — {f['foundations']} foundations, {f['components']} components, {f['patterns']} patterns |
| `04_mark/` | {f['marks']} mark, wordmark and icon files |
| `10_assets/` | {f['assets']} ready-made images at exact platform sizes |
| `11_site/` | The website, generated from the tokens |
| `12_packages/` | The tokens as an npm package and a Python package |
| `13_plugins/` | A Figma plugin and a Claude Code plugin |
| `01_research/` | What was checked, when, and against which source — including what could not be verified |

## Try it in one minute

```bash
npm install aninda-studio-tokens
```

```bash
./.venv/bin/python 00_sandbox/measure.py
```

That second command opens a real browser and re-measures every colour pairing
against the pixels it actually produced. It takes about a minute and it either
agrees with the token files or tells you exactly where it does not.

```bash
./.venv/bin/python 13_plugins/claude-code/skills/aninda-brand/scripts/asset.py --mark --size 12
```

**That last one fails on purpose.** Twelve pixels is below the mark's size floor,
so the script refuses rather than producing something unreadable. A system that
warns teaches nothing; one that refuses teaches the rule.

## Rebuild everything

Each step reads the output of the ones above it.

```bash
./.venv/bin/python 05_colour/engine.py && ./.venv/bin/python 07_tokens/build.py && ./.venv/bin/python 07_tokens/emit_css.py && ./.venv/bin/python 04_mark/build.py && ./.venv/bin/python 08_components/build.py && ./.venv/bin/python 09_guidebook/build.py
```

Every generator is fail-closed: if a check does not pass, it writes nothing at
all. A half-written token set that looks plausible is worse than none.

## What this does not do

Stated here rather than discovered later:

- **Nothing has been tested with a screen reader by somebody who depends on one.**
  Contrast is computed and proved. Lived accessibility is a different claim and
  this kit does not make it.
- **No user research.** One person's judgement, and it says so.
- **The Bangla has not been reviewed by a second Bangla reader.** Spelling follows
  the Bangla Academy standard and every ruling is sourced, but sourced is not the
  same as read well. {f['cards_bn']} of {f['cards']} cards carry Bangla names.
- **Rendering checks are Chromium on macOS only.** Safari, Firefox and real
  Windows High Contrast were not run.
- **The icons are rounded everywhere, Apple included.** That is a deliberate
  choice against Apple's current guidance, and what it trades away is recorded in
  `04_mark/manifest.json`.

## Licence

Four licences, because the parts genuinely differ. `NOTICE` explains each one.

- **The system** — tokens, stylesheets, components, scripts: **Apache-2.0**. Use
  it commercially, change it, ship it.
- **The writing** — the guidebook and the documents: **PolyForm Noncommercial
  1.0.0**. Free to read, copy and adapt; not to resell. This is
  source-available, **not open source**, and licence scanners will flag it.
- **The typefaces** — Literata, Noto Serif Bengali, IBM Plex Mono: **SIL OFL 1.1**,
  each licence beside its file.
- **The name and the marks** — **not licensed at all**. Take the system, leave the
  identity. See `TRADEMARKS.md`.

Questions and permissions: **{EMAIL}**

*Not legal advice — written by the author, who is not a lawyer.*
"""


def bangla(f: dict) -> str:
    """Written as Bangla, not translated from the English.

    Same facts, same steps, its own sentences. Only vocabulary approved in
    06_type/BANGLA-STANDARD.md and bangla-strings.json is used; where no approved
    term exists, the English word stands, which is honest rather than invented.
    """
    return f"""<!-- GENERATED by scripts/readme.py — do not hand-edit. -->

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="10_assets/README-header-dark.png">
    <img src="10_assets/README-header-light.png" alt="অনিন্দ্য স্টুডিও" width="640">
  </picture>
</p>

# অনিন্দ্য স্টুডিও

**এক জনের গড়া একটি ব্র্যান্ড ও ডিজাইন পদ্ধতি — যেখানে প্রতিটি দাবি মেপে দেখা
হয়েছে, শুধু বলা হয়নি।**

*Aninda Studio · [Read in English](README.md)*

আমি ছোটো, যত্নে গড়া সফটওয়্যার বানাই। কোনো কিছুর সীমা থাকলে সেটা এখানেই লেখা
থাকবে — লুকিয়ে রাখা হবে না।

## মূল কথাটা

**এখানের প্রতিটি রঙের জোড়া মেপে নেওয়া, বেছে নেওয়া নয়।**

{f['themes']}টি থিমে মোট **{f['pairs']}টি জোড়া** আছে — আলো, অন্ধকার, আর বেশি
কনট্রাস্টের দুটি। প্রতিটি জোড়া যে যে পৃষ্ঠের উপর বসতে পারে, সবগুলোর সঙ্গে মেপে
দেখা হয়েছে। মাপা হয়েছে সেই ৮-বিট হেক্স মানে, ব্রাউজার আসলে যেটা দেখায় — তারপর
দুই রঙের প্রতিটি চ্যানেল এক বিট সরিয়ে আবার মাপা হয়েছে। যেটা প্রকাশ করা হয়েছে,
সেটা এই সবের মধ্যে সবচেয়ে খারাপ ফলাফল।

- **লেখার জন্য {f['n_text']}টি জোড়া।** সবচেয়ে কম **{f['worst_text']}:1** —
  সাধারণ থিমে সীমা ৪.৫:১, বেশি কনট্রাস্টে ৭:১।
- **লেখা ছাড়া {f['n_nontext']}টি জোড়া** — সীমারেখা আর ফোকাস রিং। সবচেয়ে কম
  **{f['worst_nontext']}:1** — সীমা ৩:১।

দুটি আলাদা করে গোনা হয়েছে, কারণ **লেখা ছাড়া কনট্রাস্টের জন্য WCAG-এ AAA স্তর
নেই**। তাই ৩.৯:১ মানের একটি সীমারেখা তার নিয়ম পুরোপুরি মেনেছে; ৪.৫:১ দিয়ে বিচার
করলে উত্তীর্ণকে ব্যর্থ বলা হবে।

তাই এখানে হাতে লেখা কোনো কনট্রাস্টের সংখ্যা নেই। মানুষের হাতে লেখা সংখ্যা ভুল
হতে পারে, আর ভুল থেকেই যেতে পারে।

## এখানে কী আছে

| ফোল্ডার | কী আছে |
|---|---|
| `09_guidebook/` | **নির্দেশিকা।** বাংলা ও ইংরেজিতে {f['chapters']}টি অধ্যায়, একটি ফাইলেই ({f['guidebook_mb']} মেগাবাইট), ইন্টারনেট ছাড়াই চলে। সঙ্গে {f['pdf_mb']} মেগাবাইটের PDF |
| `07_tokens/` | ডিজাইন টোকেন — DTCG সূত্র, আর তা থেকে বানানো {f['tokens']}টি CSS প্রপার্টি |
| `08_components/` | {f['cards']}টি উপাদান ও নকশার কার্ড |
| `04_mark/` | চিহ্ন, নামলিপি আর আইকনের {f['marks']}টি ফাইল |
| `10_assets/` | নানা মাপে তৈরি {f['assets']}টি ছবি |
| `11_site/` | ওয়েবসাইট, টোকেন থেকে বানানো |
| `12_packages/` | টোকেনগুলো npm ও Python প্যাকেজ হিসেবে |
| `13_plugins/` | Figma প্লাগইন আর Claude Code প্লাগইন |

## শুরু করতে

```bash
npm install aninda-studio-tokens
```

```bash
./.venv/bin/python 00_sandbox/measure.py
```

এই দ্বিতীয় কমান্ডটি সত্যিকারের একটি ব্রাউজার খুলে প্রতিটি রঙের জোড়া আবার মেপে
দেখে। এক মিনিট লাগে। হয় সে টোকেন ফাইলের সঙ্গে একমত হবে, নয়তো ঠিক কোথায় মেলে না
তা বলে দেবে।

## যা এই পদ্ধতি করে না

- **কোনো স্ক্রিন রিডার ব্যবহারকারী এটি পরীক্ষা করেননি।** কনট্রাস্ট মাপা হয়েছে ও
  প্রমাণ করা হয়েছে। কিন্তু বাস্তবে ব্যবহারের সুবিধা আলাদা দাবি, আর সেই দাবি এখানে
  করা হয়নি।
- **কোনো ব্যবহারকারী গবেষণা হয়নি।** এক জনের বিচার, এবং সেটা স্পষ্ট করেই বলা।
- **দ্বিতীয় কোনো বাংলা পাঠক এই বাংলা দেখেননি।** বানান বাংলা একাডেমির প্রমিত
  নিয়ম মেনে, প্রতিটি সিদ্ধান্তের সূত্র দেওয়া — তবু সূত্র থাকা আর ভালো পড়া এক
  জিনিস নয়।
- **পরীক্ষা শুধু Chromium ও macOS-এ।** Safari, Firefox আর উইন্ডোজের হাই কনট্রাস্ট
  পরীক্ষা করা হয়নি।

## লাইসেন্স

চারটি আলাদা লাইসেন্স, কারণ অংশগুলো সত্যিই আলাদা। বিস্তারিত `NOTICE` ফাইলে।

- **পদ্ধতি** — টোকেন, স্টাইলশিট, উপাদান, স্ক্রিপ্ট: **Apache-2.0**। বাণিজ্যিক
  কাজেও ব্যবহার করা যায়।
- **লেখা** — নির্দেশিকা ও নথিপত্র: **PolyForm Noncommercial 1.0.0**। পড়া, নকল
  করা, বদলানো যায়; বিক্রি করা যায় না। এটি উৎস-উন্মুক্ত, **ওপেন সোর্স নয়**।
- **হরফ** — Literata, Noto Serif Bengali, IBM Plex Mono: **SIL OFL 1.1**।
- **নাম ও চিহ্ন** — **কোনো লাইসেন্স নেই**। পদ্ধতি নিন, পরিচয়টি রেখে দিন।

প্রশ্ন বা অনুমতির জন্য: **{EMAIL}**

*এটি আইনি পরামর্শ নয় — লেখক আইনজীবী নন।*
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    f = count()
    files = {ROOT / "README.md": english(f), ROOT / "README.bn.md": bangla(f)}

    for k, v in f.items():
        print(f"  counted  {k:<14} {v}")

    if args.check:
        for path, content in files.items():
            if not path.exists():
                print(f"\n--check: {path.name} is missing", file=sys.stderr)
                return 1
            if path.read_text() != content:
                print(f"\n--check: {path.name} differs from a fresh build — the counts "
                      f"in it have gone stale. Run scripts/readme.py.", file=sys.stderr)
                return 1
        print("\n--check: both READMEs match the repository they describe.")
        return 0

    for path, content in files.items():
        path.write_text(content)
    print(f"\nWrote README.md and README.bn.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
